loc='mypc';
% loc='cluster';
if strcmp(loc,'mypc');
pcdir='Z:/claire/'; slash='/';
else
pcdir='/jukebox/hasson/claire/'; slash='/';
end

% video_width=1592;
% video_height=848;
% vid_FrameRate=17.7296;
r=[130 255;10 50; 10 50];
b=[0 55;85 135; 150 255];
p=[200 255; 100 150; 150 200 ];
y=[50 55; 80 85; 130 135];


expdir = [pcdir 'tennis' slash ''];
exprawdir=[pcdir 'tennis_raw' slash ''];
dcmdir_nI=[exprawdir '' slash 'dcm_notInterpolated' slash ''];
dcmdir_wI=[exprawdir '' slash 'dcm_wrongInfo' slash ''];
dcmdir=[exprawdir '' slash 'dcm' slash ''];
niidir=[exprawdir '' slash 'nifti' slash ''];
scriptsdir=[expdir '' slash 'scripts' slash ''];
videodir=[expdir slash 'video' slash];

addpath([scriptsdir '' slash 'isc_nifti_kit_080916' slash '']);
addpath([scriptsdir '' slash 'isc_nifti_kit_080916' slash '' '' slash 'NIFTI_tools']);
addpath([scriptsdir 'iscstats']);
addpath([expdir '' slash 'scripts_claire' slash '']);
addpath([expdir 'scripts_claire']);

pairNames_old=...
    {'0817_Pair4',...
    '0824_Pair5',...
    '0831_Pair6',...
    '0907_Pair7',...
    '1005_Pair8',...
    '1012_Pair9',...
    '1019_Pair10',...
    '1026_Pair11'};

tr=2;

% scanN=readtable([expdir 'scanN.txt'],'Delimiter',' ');
start_scan=11;
end_scan=210;
voln=end_scan-start_scan+1;

iscpair=[4:11];
iscpair_sortAsChar=sort(arrayfun(@(x) sprintf('%d',x),iscpair,'uni',false)');

schools={'nccu','nymu'};
condition_orders={'comp1','coop1','coop2','comp2','basecomp','basecoop';
    'coop1','comp1','comp2','coop2','basecoop','basecomp';
    'comp1','coop1','coop2','comp2','basecoop','basecomp';
    'coop1','comp1','comp2','coop2','basecomp','basecoop';
    'basecoop','basecomp', 'coop1','comp1','comp2','coop2';
    'basecoop','basecomp', 'comp1','coop1','coop2','comp2';
    'basecomp','basecoop', 'coop1','comp1','comp2','coop2';
    'basecomp','basecoop', 'comp1','coop1','coop2','comp2'
    };

conditions={'coop1','coop2','comp1','comp2','basecoop','basecomp'};
conditions2={'coop','comp','basecoop','basecomp'};

rois_Juelich={...
    'BA2_L_3mm_thr20mask.nii',...
    'BA2_R_3mm_thr20mask.nii',...
    'BA6_L_3mm_thr20mask.nii',...
    'BA6_R_3mm_thr20mask.nii',...
    'SPL_5L_L_3mm_thr20mask.nii',...
    'SPL_5L_R_3mm_thr20mask.nii',...
    'V1_L_3mm_thr20mask.nii',...
    'V1_R_3mm_thr20mask.nii',...
    'V2_L_3mm_thr20mask.nii',...
    'V2_R_3mm_thr20mask.nii',...
    'V3v_L_3mm_thr20mask.nii',...
    'V3v_R_3mm_thr20mask.nii',...
    'V4_L_3mm_thr20mask.nii',...
    'V4_R_3mm_thr20mask.nii',...
    'V5_L_3mm_thr20mask.nii',...
    'V5_R_3mm_thr20mask.nii'};

rois_Oxford={...
    'Intracalcarine_L_3mm_thr20mask.nii',...
    'Intracalcarine_R_3mm_thr20mask.nii',...
    'Lingual_L_3mm_thr20mask.nii',...
    'Lingual_R_3mm_thr20mask.nii',...
    'LOCinf_L_3mm_thr20mask.nii',...
    'LOCinf_R_3mm_thr20mask.nii',...
    'Postcentral_L_3mm_thr20mask.nii',...
    'Postcentral_R_3mm_thr20mask.nii',...
    'Precentral_L_3mm_thr20mask.nii',...
    'Precentral_R_3mm_thr20mask.nii',...
    'SMA_L_3mm_thr20mask.nii',....
    'SMA_R_3mm_thr20mask.nii',...
    'SPL_3mm_thr20mask.nii',...
    'SPL_L_3mm_thr20mask.nii',...
    'SPL_R_3mm_thr20mask.nii'};

input_types= {'trans_filtered_func' , 'trans_res4d'}; %